In [3]:
!pip install pandas numpy Faker

Requirement already satisfied: pandas in c:\users\ajinkya\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\ajinkya\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: Faker in c:\users\ajinkya\anaconda3\lib\site-packages (37.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ajinkya\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ajinkya\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ajinkya\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\ajinkya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [34]:
import pandas as pd
from datetime import datetime, timedelta
from faker import Faker
import numpy as np
import random

In [36]:
start_date = datetime(2023, 1, 1)
end_date = datetime(2025, 1, 1)
date_range = pd.date_range(start=start_date, end=end_date)

dim_date = pd.DataFrame({
    'date_actual': date_range
})
dim_date['date_id'] = dim_date['date_actual'].dt.strftime('%Y%m%d').astype(int)
dim_date['day_of_week'] = dim_date['date_actual'].dt.day_name()
dim_date['week_of_year'] = dim_date['date_actual'].dt.isocalendar().week
dim_date['month'] = dim_date['date_actual'].dt.month
dim_date['quarter'] = dim_date['date_actual'].dt.quarter
dim_date['year'] = dim_date['date_actual'].dt.year
dim_date['is_weekend'] = dim_date['day_of_week'].isin(['Saturday', 'Sunday'])

dim_date.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_date.csv", index=False)

In [38]:
indian_hubs = [
    ('Mumbai', 'MH'), ('Delhi', 'DL'), ('Bengaluru', 'KA'), ('Hyderabad', 'TG'),
    ('Ahmedabad', 'GJ'), ('Chennai', 'TN'), ('Kolkata', 'WB'), ('Pune', 'MH'),
    ('Jaipur', 'RJ'), ('Lucknow', 'UP'), ('Kanpur', 'UP'), ('Nagpur', 'MH'),
    ('Indore', 'MP'), ('Thane', 'MH'), ('Bhopal', 'MP'), ('Visakhapatnam', 'AP'),
    ('Patna', 'BR'), ('Vadodara', 'GJ'), ('Ghaziabad', 'UP'), ('Ludhiana', 'PB'),
    ('Agra', 'UP'), ('Nashik', 'MH'), ('Faridabad', 'HR'), ('Meerut', 'UP'),
    ('Rajkot', 'GJ'), ('Kalyan', 'MH'), ('Vasai-Virar', 'MH'), ('Varanasi', 'UP'),
    ('Srinagar', 'JK'), ('Aurangabad', 'MH'), ('Dhanbad', 'JH'), ('Amritsar', 'PB'),
    ('Navi Mumbai', 'MH'), ('Allahabad', 'UP'), ('Ranchi', 'JH'), ('Howrah', 'WB'),
    ('Coimbatore', 'TN'), ('Jabalpur', 'MP'), ('Gwalior', 'MP'), ('Vijayawada', 'AP'),
    ('Jodhpur', 'RJ'), ('Madurai', 'TN'), ('Raipur', 'CG'), ('Kota', 'RJ'),
    ('Guwahati', 'AS'), ('Chandigarh', 'CH'), ('Solapur', 'MH'), ('Hubliâ€“Dharwad', 'KA'),
    ('Mysore', 'KA'), ('Tiruchirappalli', 'TN'), ('Bareilly', 'UP'), ('Aligarh', 'UP'),
    ('Moradabad', 'UP'), ('Jalandhar', 'PB'), ('Bhubaneswar', 'OD'), ('Salem', 'TN'),
    ('Warangal', 'TG'), ('Guntur', 'AP'), ('Bhiwandi', 'MH'), ('Saharanpur', 'UP'),
    ('Gorakhpur', 'UP'), ('Bikaner', 'RJ'), ('Amravati', 'MH'), ('Noida', 'UP'),
    ('Jamshedpur', 'JH'), ('Bhilai', 'CG'), ('Cuttack', 'OD'), ('Firozabad', 'UP'),
    ('Kochi', 'KL'), ('Nellore', 'AP'), ('Bhavnagar', 'GJ'), ('Dehradun', 'UK'),
    ('Durgapur', 'WB'), ('Asansol', 'WB'), ('Rourkela', 'OD'), ('Nanded', 'MH'),
    ('Kolhapur', 'MH'), ('Ajmer', 'RJ'), ('Akola', 'MH'), ('Gulbarga', 'KA'),
    ('Jamnagar', 'GJ'), ('Ujjain', 'MP'), ('Loni', 'UP'), ('Siliguri', 'WB'),
    ('Jhansi', 'UP'), ('Ulhasnagar', 'MH'), ('Nellore', 'AP'), ('Bilaspur', 'CG'),
    ('Shimla', 'HP'), ('Panipat', 'HR'), ('Bharatpur', 'RJ'), ('Gandhinagar', 'GJ'),
    ('Pimpri-Chinchwad', 'MH'), ('Anantapur', 'AP'), ('Dewas', 'MP'), ('Karnal', 'HR'),
    ('Tirunelveli', 'TN'), ('Bathinda', 'PB'), ('Rewa', 'MP'), ('Satna', 'MP')
]

dim_hub = pd.DataFrame([{
    'hub_id': i + 1,
    'hub_name': f"{city} Hub",
    'location_city': city,
    'location_state': state,
    'manager_name': f"Manager_{i + 1}",
    'capacity_packages_per_hour': random.randint(150, 500)
} for i, (city, state) in enumerate(indian_hubs)])

dim_hub.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_hub.csv", index=False)

In [40]:
fake = Faker()
hub_cities = dim_hub['location_city'].tolist()
shifts = ['Morning', 'Evening', 'Night']

dim_driver = pd.DataFrame({
    'driver_id': range(1, 101),
    'driver_name': [fake.name() for _ in range(100)],
    'region': random.choices(hub_cities, k=100),
    'experience_years': np.random.randint(1, 15, size=100),
    'shift': random.choices(shifts, k=100)
})

dim_driver.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_driver.csv", index=False)

In [42]:
dim_vehicle = pd.DataFrame({
    'vehicle_id': [1, 2, 3, 4],
    'vehicle_type': ['Bike', 'Van', 'Mini Truck', 'Truck'],
    'capacity_kg': [100, 1000, 2000, 5000],
    'average_speed_kmph': [45, 50, 55, 60],
    'fuel_usage_l_per_100km': [4, 8, 12, 15]
})
dim_vehicle.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_vehicle.csv", index=False)

In [44]:
package_types = ['Document', 'Small Parcel', 'Large Box']
priorities = ['Standard', 'Express']

dim_package = pd.DataFrame({
    'package_id': list(range(1, 101)),
    'size': np.random.choice(['S', 'M', 'L'], 100),
    'weight': np.round(np.random.uniform(0.1, 30, size=100), 2),
    'priority': random.choices(priorities, k=100),
    'type': random.choices(package_types, k=100)
})
dim_package.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_package.csv", index=False)

In [46]:
origin_dest = [(o, d) for o in hub_cities for d in hub_cities if o != d]
route_sample = random.sample(origin_dest, 100)

dim_route = pd.DataFrame([{
    'route_id': i + 1,
    'origin_location': origin,
    'destination_location': dest,
    'distance_km': random.randint(20, 600),
    'average_time_minutes': random.randint(30, 360)
} for i, (origin, dest) in enumerate(route_sample)])

dim_route.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_route.csv", index=False)

In [48]:
start_date = datetime(2023, 1, 1)
end_date = datetime(2024, 12, 31)
date_range = pd.date_range(start=start_date, end=end_date)

fog_levels = ['None', 'Low', 'Medium', 'High']
weather_data = []
weather_id = 1

for date in date_range:
    for city in hub_cities:
        temp = round(np.random.normal(loc=30, scale=5), 1)
        precip = max(0, round(np.random.exponential(scale=5), 1))
        fog = random.choices(fog_levels, weights=[0.4, 0.3, 0.2, 0.1])[0]
        if fog != 'None':
            condition = 'Foggy'
        elif precip > 5:
            condition = 'Rainy'
        else:
            condition = random.choice(['Sunny', 'Cloudy'])
        
        weather_data.append([
            weather_id, city, int(date.strftime('%Y%m%d')),
            date.strftime('%H:%M:%S'), temp, precip, fog, condition
        ])
        weather_id += 1

dim_weather = pd.DataFrame(weather_data, columns=[
    'weather_id', 'region', 'date_id', 'time_of_day',
    'temperature_c', 'precipitation_mm', 'fog_intensity', 'weather_condition'
])

dim_weather.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_weather.csv", index=False)

In [56]:
# Load your dimension tables
dim_date = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_date.csv")
dim_driver = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_driver.csv")
dim_hub = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_hub.csv")
dim_vehicle = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_vehicle.csv")
dim_package = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_package.csv")
dim_route = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_route.csv")
dim_weather = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\dim_weather.csv")


# Generate fact_delivery records
fact_data = []
num_records = 50000
np.random.seed(42)

for delivery_id in range(1, num_records + 1):
    package_id = random.choice(dim_package['package_id'])
    driver_id = random.choice(dim_driver['driver_id'])
    vehicle_id = random.choice(dim_vehicle['vehicle_id'])

    route_row = dim_route.sample(1).iloc[0]
    route_id = route_row['route_id']
    origin_location = route_row['origin_location']
    destination_location = route_row['destination_location']
    avg_minutes = route_row['average_time_minutes']

    date_row = dim_date.sample(1).iloc[0]
    delivery_date_id = date_row['date_id']
    delivery_date = pd.to_datetime(date_row['date_actual'])

    # Expected delivery time based on route time and shift
    expected_delivery_time = delivery_date + timedelta(hours=random.randint(8, 20))
    expected_delivery_time += timedelta(minutes=int(avg_minutes))

    # Simulate delay
    delay_choices = [0, 5, 10, 20, 30, 45, 60, 90, 120]
    delay_weights = [0.2, 0.25, 0.2, 0.1, 0.08, 0.05, 0.04, 0.04, 0.04]
    delay_minutes = np.random.choice(delay_choices, p=delay_weights)

    actual_delivery_time = expected_delivery_time + timedelta(minutes=int(delay_minutes))

    if delay_minutes <= 5:
        status = "Delivered"
        on_time_flag = 1
    elif delay_minutes <= 60:
        status = "Delayed"
        on_time_flag = 0
    else:
        status = "Failed"
        on_time_flag = 0

    # Get weather_id by matching region and date
    weather_matches = dim_weather[
        (dim_weather['region'] == origin_location) &
        (dim_weather['date_id'] == delivery_date_id)
    ]
    if not weather_matches.empty:
        weather_id = weather_matches.sample(1).iloc[0]['weather_id']
    else:
        weather_id = np.nan  # fallback

    fact_data.append([
        delivery_id, package_id, driver_id, route_id,
        origin_location, destination_location, vehicle_id,
        status, actual_delivery_time, expected_delivery_time,
        delay_minutes, delivery_date_id, on_time_flag, weather_id
    ])

# Create DataFrame
fact_delivery = pd.DataFrame(fact_data, columns=[
    'delivery_id', 'package_id', 'driver_id', 'route_id',
    'origin_location', 'destination_location', 'vehicle_id',
    'status', 'actual_delivery_time', 'expected_delivery_time',
    'delay_minutes', 'delivery_date_id', 'on_time_flag', 'weather_id'
])

# Save to CSV
fact_delivery.to_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\fact_delivery.csv", index=False)

In [64]:
fact = pd.read_csv(r"C:\Users\AJINKYA\Desktop\Logistics Bottleneck & Delay Analyzer\Original Datasets\fact_delivery.csv")

In [65]:
fact

,delivery_id,package_id,driver_id,route_id,origin_location,destination_location,vehicle_id,status,actual_delivery_time,expected_delivery_time,delay_minutes,delivery_date_id,on_time_flag,weather_id
0,1,11,2,84,Moradabad,Chennai,3,Delivered,2024-05-08 17:52:00,2024-05-08 17:52:00,0,20240508,1,49353.0
1,2,18,21,29,Rewa,Tiruchirappalli,3,Delayed,2023-07-25 23:53:00,2023-07-25 23:43:00,10,20230725,0,20599.0
2,3,94,42,64,Tirunelveli,Shimla,4,Delayed,2023-02-06 18:09:00,2023-02-06 17:59:00,10,20230206,0,3697.0
3,4,59,92,14,Gwalior,Noida,1,Delayed,2024-10-13 20:12:00,2024-10-13 20:02:00,10,20241013,0,65139.0
4,5,80,47,60,Ulhasnagar,Panipat,3,Delayed,2023-10-02 20:30:00,2023-10-02 20:10:00,20,20231002,0,27486.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,68,69,16,Bathinda,Amravati,3,Delivered,2024-11-06 13:23:00,2024-11-06 13:23:00,0,20241106,1,67598.0
49996,49997,76,40,56,Karnal,Gwalior,1,Delivered,2024-08-03 18:08:00,2024-08-03 18:03:00,5,20240803,1,58096.0
49997,49998,8,27,34,Ajmer,Guntur,2,Delivered,2023-02-01 22:32:00,2023-02-01 22:32:00,0,20230201,1,3178.0
49998,49999,33,34,67,Visakhapatnam,Lucknow,3,Delayed,2024-10-19 21:04:00,2024-10-19 20:44:00,20,20241019,0,65716.0
49999,50000,88,38,100,Jaipur,Bhubaneswar,3,Delivered,2023-07-30 21:06:00,2023-07-30 21:01:00,5,20230730,1,21009.0

,delivery_id,package_id,driver_id,route_id,origin_location,destination_location,vehicle_id,status,actual_delivery_time,expected_delivery_time,delay_minutes,delivery_date_id,on_time_flag,weather_id
0,1,11,2,84,Moradabad,Chennai,3,Delivered,2024-05-08 17:52:00,2024-05-08 17:52:00,0,20240508,1,49353.0
1,2,18,21,29,Rewa,Tiruchirappalli,3,Delayed,2023-07-25 23:53:00,2023-07-25 23:43:00,10,20230725,0,20599.0
2,3,94,42,64,Tirunelveli,Shimla,4,Delayed,2023-02-06 18:09:00,2023-02-06 17:59:00,10,20230206,0,3697.0
3,4,59,92,14,Gwalior,Noida,1,Delayed,2024-10-13 20:12:00,2024-10-13 20:02:00,10,20241013,0,65139.0
4,5,80,47,60,Ulhasnagar,Panipat,3,Delayed,2023-10-02 20:30:00,2023-10-02 20:10:00,20,20231002,0,27486.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,68,69,16,Bathinda,Amravati,3,Delivered,2024-11-06 13:23:00,2024-11-06 13:23:00,0,20241106,1,67598.0
49996,49997,76,40,56,Karnal,Gwalior,1,Delivered,2024-08-03 18:08:00,2024-08-03 18:03:00,5,20240803,1,58096.0
49997,49998,8,27,34,Ajmer,Guntur,2,Delivered,2023-02-01 22:32:00,2023-02-01 22:32:00,0,20230201,1,3178.0
49998,49999,33,34,67,Visakhapatnam,Lucknow,3,Delayed,2024-10-19 21:04:00,2024-10-19 20:44:00,20,20241019,0,65716.0
49999,50000,88,38,100,Jaipur,Bhubaneswar,3,Delivered,2023-07-30 21:06:00,2023-07-30 21:01:00,5,20230730,1,21009.0